"""LangGraph graph definition for the Publish Post Agent.

Graph flow:
    START → resolve_and_validate → golden_hour → route_schedule
      ├─ "publish_now"  → publish → END
      └─ "schedule"     → schedule_job → END
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

import structlog
from langgraph.graph import END, START, StateGraph
from sqlalchemy import select

from app.agents.publish_post.caption_assembler import assemble_caption
from app.agents.publish_post.golden_hour import golden_hour_node
from app.agents.publish_post.publish_node import publish_node
from app.agents.publish_post.scheduler_node import scheduler_node
from app.agents.publish_post.state import PublishPostState
from app.agents.publish_post.token_manager import get_valid_token
from app.core.exceptions import ApiError
from app.core.storage import get_storage
from app.db.models.content_post import ContentPost
from app.db.models.enums import ContentStatus, PublishMode, PublishStatus
from app.db.models.published_post import PublishedPost
from app.db.session import async_session_factory

logger = structlog.get_logger()


async def resolve_and_validate_node(state: PublishPostState) -> dict:
    """Resolve all data needed for publishing:

    1. Load ContentPost from DB, validate status = approved
    2. Create PublishedPost record
    3. Resolve image public URL via StorageBackend
    4. Assemble caption (caption + hashtags + CTA)
    5. Validate TikTok token exists
    """
    content_post_id = state["content_post_id"]
    publish_mode = state.get("publish_mode", "auto")

    async with async_session_factory() as db:
        # Load content post
        result = await db.execute(
            select(ContentPost).where(ContentPost.id == uuid.UUID(content_post_id))
        )
        post = result.scalar_one_or_none()

        if not post:
            raise ValueError(f"ContentPost {content_post_id} not found")

        if post.status not in (ContentStatus.APPROVED, ContentStatus.PUBLISHED):
            raise ValueError(
                f"ContentPost {content_post_id} has status '{post.status.value}', "
                "only 'approved' posts can be published"
            )

        # Check for duplicate: already successfully published
        existing = await db.execute(
            select(PublishedPost).where(
                PublishedPost.content_post_id == post.id,
                PublishedPost.status == PublishStatus.PUBLISHED,
            )
        )
        if existing.scalar_one_or_none():
            raise ValueError(f"ContentPost {content_post_id} is already published")

        # Create published_post record
        import uuid as _uuid

        _user_id_raw = state.get("user_id") or ""
        pub = PublishedPost(
            content_post_id=post.id,
            published_by=_uuid.UUID(_user_id_raw) if _user_id_raw else None,
            publish_mode=PublishMode(publish_mode),
            status=PublishStatus.PROCESSING,
            privacy_level=state.get("privacy_level", "SELF_ONLY"),
        )
        db.add(pub)
        await db.flush()
        published_post_id = str(pub.id)

        # Assemble caption
        hashtags = post.hashtags or []
        caption = assemble_caption(
            caption=post.caption,
            hashtags=hashtags,
            cta=post.cta,
        )
        pub.assembled_caption = caption

        # Resolve image public URL
        storage = get_storage()
        image_key = post.image_path or ""
        if not image_key or not storage.exists(image_key):
            raise ValueError(
                f"Thumbnail not found at '{image_key}'. "
                "Ensure the image was generated by the Visual Factory."
            )
        image_public_url = storage.get_public_url(image_key)

        # Validate token exists (don't decrypt yet — just check)
        try:
            access_token, open_id = await get_valid_token(db)
        except ApiError as e:
            pub.status = PublishStatus.FAILED
            pub.error_message = str(e)
            await db.commit()
            raise

        await db.commit()

    logger.info(
        "resolve: validated",
        content_post_id=content_post_id,
        published_post_id=published_post_id,
        image_url=image_public_url[:80],
    )

    return {
        "published_post_id": published_post_id,
        "assembled_caption": caption,
        "image_public_url": image_public_url,
        "access_token": access_token,
        "tiktok_open_id": open_id,
    }


def _route_after_schedule(state: PublishPostState) -> str:
    """Conditional edge: publish now or schedule for later."""
    status = state.get("publish_status", "")
    if status == "publish_now":
        return "publish"
    return END  # "scheduled" — APScheduler will trigger publish later


def build_publish_graph() -> StateGraph:
    """Build and compile the Publish Post Agent graph."""
    graph = StateGraph(PublishPostState)

    graph.add_node("resolve_and_validate", resolve_and_validate_node)
    graph.add_node("golden_hour", golden_hour_node)
    graph.add_node("scheduler", scheduler_node)
    graph.add_node("publish", publish_node)

    graph.add_edge(START, "resolve_and_validate")
    graph.add_edge("resolve_and_validate", "golden_hour")
    graph.add_edge("golden_hour", "scheduler")

    graph.add_conditional_edges(
        "scheduler",
        _route_after_schedule,
        {
            "publish": "publish",
            END: END,
        },
    )
    graph.add_edge("publish", END)

    return graph.compile()
